#!/bin/sh

cleanup_function() {
  # Stop server and client
  pm2 delete server
  pm2 delete client
}

trap cleanup_function SIGINT

cd ..
# Setup test DB
npm run db:setup-test
# Stop server and client if they are running
pm2 delete server
pm2 delete client
# Start server and client
npx pm2 start npm --name "server" -- run start:test-headless
npx pm2 start npm --name "client" -- run start:test-headless --prefix client
# Run Cypress tests
npm run cypress:headless --prefix client
# Stop server and client
pm2 delete server
pm2 delete client