#!/bin/sh
ssh charuk@167.99.145.25 <<EOF
 cd ~/hvoya-crm
 npm run db:backup
 git checkout .
 git pull
 cd ~/hvoya-crm/client
 npm install
 cd ~/hvoya-crm
 npm install
 npm run build
 cd ~/hvoya-crm/client
 npm run build
 cd ~/hvoya-crm
 npm run migrations:run
 pm2 restart all
 exit
EOF