export enum ErrorCode {
  UNKNOWN_REQUEST = 1,
  USER_NOT_FOUND = 2,
  FOUNDS_ERROR = 3,
  INVALID_DATA = 4,
  IP_NOT_ALLOWED = 5,
  MORE_THAN_ONE_USER_FOUND = 6,
  USER_DUPLICATE = 7,
  CRITICAL_ERROR = 8,
  ANOTHER_ERROR = 99,
}
