#!/bin/sh

cleanup_function() {
  # Stop server and client
  pm2 delete server
  pm2 delete client
  exit 1
}

trap cleanup_function INT TERM

cd ..
# Setup test DB
npm run db:setup-test
# Stop server and client if they are running
pm2 delete server
pm2 delete client
# Start server and client
npx pm2 start npm --name "server" -- run start:test-headless
npx pm2 start npm --name "client" -- run start:test-headless --prefix client
# Wait for server and client to start
echo "Waiting for server and client to start..."
sleep 20
# Run Cypress tests
npm run start:headless --prefix e2e
# Stop server and client
pm2 delete server
pm2 delete client
exit 0