// TODO: remove this file when the API is ready
export default [
  {
    id: 1,
    name: 'Product 1',
    category: {
      id: 1,
      name: 'Category 1',
    },
    variants: [
      {
        id: 1,
        sku: 'SKU-1',
        name: 'Variant 1',
        description: 'Description 1',
        price: 100,
        size: '120cm',
        color: 'blue',
        availableItemCount: 10,
      },
      {
        id: 2,
        sku: 'SKU-2',
        name: 'Variant 2',
        description: 'Description 2',
        price: 200,
        size: '140cm',
        color: 'green',
        availableItemCount: 20,
      },
      {
        id: 3,
        sku: 'SKU-3',
        name: 'Variant 3',
        description: 'Description 3',
        price: 300,
        size: '120cm',
        color: 'red',
        availableItemCount: 30,
      },
      {
        id: 125,
        sku: 'SKU-125',
        name: 'Variant 125',
        description: 'Description 125',
        price: 300,
        size: '140cm',
        color: 'black',
        availableItemCount: 30,
      },
    ],
  },
  {
    id: 2,
    name: 'Product 2',
    category: {
      id: 2,
      name: 'Category 2',
    },
    variants: [
      {
        id: 4,
        sku: 'SKU-4',
        name: 'Variant 4',
        description: 'Description 4',
        price: 400,
        size: '120cm',
        color: 'blue',
        availableItemCount: 40,
      },
      {
        id: 5,
        sku: 'SKU-5',
        name: 'Variant 5',
        description: 'Description 5',
        price: 500,
        size: '140cm',
        color: 'green',
        availableItemCount: 50,
      },
    ],
  },
  {
    id: 3,
    name: 'Product 3',
    category: {
      id: 3,
      name: 'Category 3',
    },
    variants: [
      {
        id: 6,
        sku: 'SKU-6',
        name: 'Variant 6',
        description: 'Description 6',
        price: 600,
        size: '120cm',
        color: 'blue',
        availableItemCount: 60,
      },
      {
        id: 7,
        sku: 'SKU-7',
        name: 'Variant 7',
        description: 'Description 7',
        price: 700,
        size: '140cm',
        color: 'green',
        availableItemCount: 70,
      },
    ],
  },
  {
    id: 4,
    name: 'Product 4',
    category: {
      id: 4,
      name: 'Category 4',
    },
    variants: [
      {
        id: 8,
        sku: 'SKU-8',
        name: 'Variant 8',
        description: 'Description 8',
        price: 800,
        size: '120cm',
        color: 'blue',
        availableItemCount: 80,
      },
    ],
  },
];
